const generateRealisticRating = () => {
    // Generate rating between 4.5 and 4.9
    const rating = (4.5 + Math.random() * 0.4).toFixed(1);
    // Generate review count between 1200 and 58000
    const reviewCount = Math.floor(1200 + Math.random() * 56800);
    return { rating: parseFloat(rating), reviewCount };
};

const commonDos = ["Dress conservatively", "Remove footwear", "Respect customs"];
const commonDonts = ["No photography in sanctum", "No leather items", "Maintain silence"];

const templesData = [
    {
        name: "Kashi Vishwanath Temple",
        location: "Varanasi, Uttar Pradesh",
        state: "Uttar Pradesh",
        description: "One of the most famous Hindu temples dedicated to Lord Shiva, located on the western bank of the holy river Ganga. It is one of the twelve Jyotirlingas.",
        imageUrl: "/temples/Kashi_Vishwanath/1.jpg",
        imageCredit: "Local Archive",
        ...generateRealisticRating(),
        timings: "3:00 AM - 11:00 PM",
        openHour: 3,
        closeHour: 23,
        baseWaitTime: 45,
        timingDetails: [
            "Mangala Aarti: 3:00 AM - 4:00 AM",
            "Bhog Aarti: 11:15 AM - 12:20 PM",
            "Sandhya Aarti: 7:00 PM - 8:15 PM",
            "Shayan Aarti: 10:30 PM - 11:00 PM"
        ],
        darshanTime: "1-2 hours",
        bestTimeToVisit: "Early morning (4-6 AM)",
        lat: 25.3107,
        lng: 83.0089,
        deity: "Lord Shiva",
        significance: "One of the 12 Jyotirlingas, Spiritual Capital of India",
        uniqueness: {
            spiritual: "Believed to be the center of the universe in Hindu cosmology. Dying here is believed to grant Moksha (liberation).",
            scientific: "The acoustics of the ancient mandap were designed to amplify chanting mantras.",
            history: "Rebuilt multiple times, current structure by Ahilyabai Holkar in 1780."
        },
        dos: [...commonDos, "Carry valid ID proof", "Book specific Aarti tickets online"],
        donts: [...commonDonts, "Do not touch the Shivling during peak hours"],
        crowdPattern: { type: "pilgrimage" },
        specialDays: [{ day: "Monday", multiplier: 1.6 }],
        peakMonths: [2, 7, 10, 11]
    },
    {
        name: "Tirumala Tirupati Balaji",
        location: "Tirumala, Andhra Pradesh",
        state: "Andhra Pradesh",
        description: "The richest temple in the world, situated on the Seshachalam Hills. Dedicated to Lord Venkateswara, an incarnation of Vishnu.",
        imageUrl: "/temples/Tirumala_Tirupati/1.jpg",
        imageCredit: "Local Archive",
        ...generateRealisticRating(),
        timings: "2:30 AM - 1:30 AM (Next Day)",
        openHour: 2,
        closeHour: 26, // Handles virtually 24/7
        baseWaitTime: 180,
        timingDetails: [
            "Suprabhatam: 2:30 AM",
            "Thomala Seva: 3:30 AM",
            "Ekantha Seva: 1:30 AM"
        ],
        darshanTime: "3-12 hours",
        bestTimeToVisit: "Tuesday/Wednesday",
        lat: 13.6833,
        lng: 79.3472,
        deity: "Lord Venkateswara",
        significance: "Kali Yuga Vaikuntham",
        uniqueness: {
            spiritual: "The deity is believed to be self-manifested (Swayambhu).",
            scientific: "The idol maintains a temperature of 110°F despite being stone and bathed in water/milk.",
            history: "Patronized by Pallavas, Cholas, Pandyas, and Vijayanagara kings."
        },
        dos: [...commonDos, "Book darshan months in advance", "Follow the queue discipline"],
        donts: [...commonDonts, "No flowers allowed inside"],
        crowdPattern: { type: "high_traffic" },
        specialDays: [{ day: "Saturday", multiplier: 1.5 }],
        peakMonths: [5, 6, 9, 12]
    },
    {
        name: "Vaishno Devi Temple",
        location: "Katra, Jammu & Kashmir",
        state: "Jammu & Kashmir",
        description: "A holy cave shrine dedicated to Goddess Vaishno Devi, located at an altitude of 5200 feet in the Trikuta Mountains.",
        imageUrl: "/temples/Vaishno_Devi/1.jpg",
        imageCredit: "Local Archive",
        ...generateRealisticRating(),
        timings: "5:00 AM - 11:00 PM",
        openHour: 5,
        closeHour: 23,
        baseWaitTime: 90,
        timingDetails: ["Aarti: 6:20 AM and 7:20 PM"],
        darshanTime: "4-6 hours (trek)",
        bestTimeToVisit: "March-April, September-October",
        lat: 33.0304,
        lng: 74.9499,
        deity: "Goddess Vaishno Devi",
        significance: "Shakti Peeth",
        uniqueness: {
            spiritual: "The goddess is present in the form of three natural rock formations (Pindies).",
            scientific: "Geological studies show the cave is millions of years old.",
            history: "First mentioned in the Mahabharata."
        },
        dos: [...commonDos, "Obtain Yatra slip at Katra", "Respect the environment"],
        donts: [...commonDonts, "Do not litter on the trek path"],
        crowdPattern: { type: "pilgrimage" },
        specialDays: [{ day: "Tuesday", multiplier: 1.3 }],
        peakMonths: [3, 4, 9, 10]
    },
    {
        name: "Somnath Temple",
        location: "Prabhas Patan, Gujarat",
        state: "Gujarat",
        description: "The first among the twelve Jyotirlinga shrines of Shiva. Known as the 'Shrine Eternal'.",
        imageUrl: "/temples/Somnath/1.jpg",
        imageCredit: "Local Archive",
        ...generateRealisticRating(),
        timings: "6:00 AM - 10:00 PM",
        openHour: 6,
        closeHour: 22,
        baseWaitTime: 40,
        timingDetails: ["Aarti: 7:00 AM, 12:00 PM, 7:00 PM", "Light & Sound Show: 8:00 PM"],
        darshanTime: "1 hour",
        bestTimeToVisit: "Winter months",
        lat: 20.8880,
        lng: 70.4010,
        deity: "Lord Shiva",
        significance: "First Jyotirlinga",
        uniqueness: {
            spiritual: "The Syamantaka Mani (mythical gem) is associated with this temple.",
            scientific: "A pillar (Baan Stambh) points to the South Pole with no landmass in between.",
            history: "Destroyed and rebuilt 17 times. Current style is Chalukya."
        },
        dos: [...commonDos, "Attend the evening light and sound show"],
        donts: [...commonDonts],
        crowdPattern: { type: "tourist" },
        specialDays: [{ day: "Monday", multiplier: 1.4 }],
        peakMonths: [11, 12, 1, 2]
    },
    {
        name: "Kedarnath Temple",
        location: "Kedarnath, Uttarakhand",
        state: "Uttarakhand",
        description: "One of the Chardham pilgrimage sites, located in the Himalayas near the Mandakini river.",
        imageUrl: "/temples/Kedarnath/1.jpg",
        imageCredit: "Local Archive",
        ...generateRealisticRating(),
        timings: "4:00 AM - 9:00 PM",
        openHour: 4,
        closeHour: 21,
        baseWaitTime: 60,
        timingDetails: ["Morning Aarti: 5:35 AM", "Evening Aarti: 6:00 PM to 7:30 PM"],
        darshanTime: "2-3 hours",
        bestTimeToVisit: "May-June, September-October",
        lat: 30.7352,
        lng: 79.0669,
        deity: "Lord Shiva",
        significance: "Highest Jyotirlinga",
        uniqueness: {
            spiritual: "Pandavas sought forgiveness from Shiva here.",
            scientific: "Withstood the 2013 massive flash floods due to its robust north-facing design and a large boulder (Bhim Shila) diverting water.",
            history: "Built by Adi Shankaracharya in the 8th century."
        },
        dos: [...commonDos, "Carry warm clothes even in summer", "Acclimatize for altitude"],
        donts: [...commonDonts, "Do not travel at night"],
        crowdPattern: { type: "pilgrimage" },
        specialDays: [{ day: "Monday", multiplier: 1.5 }],
        peakMonths: [5, 6]
    },
    {
        name: "Badrinath Temple",
        location: "Badrinath, Uttarakhand",
        state: "Uttarakhand",
        description: "A Hindu temple dedicated to Lord Vishnu, situated in the town of Badrinath in Uttarakhand.",
        imageUrl: "/temples/Badrinath/1.jpg",
        imageCredit: "Local Archive",
        ...generateRealisticRating(),
        timings: "4:30 AM - 9:00 PM",
        openHour: 4,
        closeHour: 21,
        baseWaitTime: 60,
        timingDetails: ["Morning Puja: 4:30 AM", "Evening Aarti: 8:30 PM"],
        darshanTime: "1-2 hours",
        bestTimeToVisit: "May-June, September-October",
        lat: 30.7433,
        lng: 79.4938,
        deity: "Lord Vishnu",
        significance: "Char Dham",
        uniqueness: {
            spiritual: "Place where Vishnu meditated in the form of a Berry tree (Badri).",
            scientific: "Hot water sulphur springs (Tapt Kund) nearby at 45°C amidst freezing cold.",
            history: "Established by Adi Shankaracharya."
        },
        dos: [...commonDos, "Take a dip in Tapt Kund before Darshan"],
        donts: [...commonDonts],
        crowdPattern: { type: "pilgrimage" },
        specialDays: [],
        peakMonths: [5, 6]
    },
    {
        name: "Ramanathaswamy Temple",
        location: "Rameswaram, Tamil Nadu",
        state: "Tamil Nadu",
        description: "A Hindu temple dedicated to the god Shiva located on Rameswaram island.",
        imageUrl: "/temples/Ramanathaswamy/1.jpg",
        imageCredit: "Local Archive",
        ...generateRealisticRating(),
        timings: "5:00 AM - 9:00 PM",
        openHour: 5,
        closeHour: 21,
        baseWaitTime: 45,
        timingDetails: ["Morning: 5:00 AM - 1:00 PM", "Evening: 3:00 PM - 9:00 PM"],
        darshanTime: "2-3 hours",
        bestTimeToVisit: "October-April",
        lat: 9.2881,
        lng: 79.3174,
        deity: "Lord Shiva",
        significance: "Jyotirlinga and Char Dham",
        uniqueness: {
            spiritual: "Lingam created by Sita and worshipped by Rama.",
            scientific: "Longest corridor in the world with 1212 pillars.",
            history: "Expanded by Pandya and Jaffna kings."
        },
        dos: [...commonDos, "Bathe in the 22 holy wells (Theerthams)"],
        donts: [...commonDonts, "Do not use soap in temple tanks"],
        crowdPattern: { type: "pilgrimage" },
        specialDays: [{ day: "Monday", multiplier: 1.4 }],
        peakMonths: [1, 12]
    },
    {
        name: "Akshardham Temple",
        location: "New Delhi, Delhi",
        state: "Delhi",
        description: "A Hindu temple complex displays millennia of traditional Hindu and Indian culture, spirituality, and architecture.",
        imageUrl: "/temples/Akshardham_Delhi/1.png",
        imageCredit: "Local Archive",
        ...generateRealisticRating(),
        timings: "9:30 AM - 8:00 PM",
        openHour: 9,
        closeHour: 20,
        baseWaitTime: 90,
        timingDetails: ["Entry closes: 6:30 PM", "Exhibitions: 10:00 AM - 8:00 PM"],
        darshanTime: "3-4 hours",
        bestTimeToVisit: "Weekdays",
        lat: 28.6127,
        lng: 77.2773,
        deity: "Swaminarayan",
        significance: "Modern Architectural Marvel",
        uniqueness: {
            spiritual: "Dedicated to Bhagwan Swaminarayan.",
            scientific: "Built without steel or concrete, using only interlocked stone.",
            history: "Opened in 2005."
        },
        dos: [...commonDos, "Keep mobile phones in cloakroom", "Enjoy the musical fountain"],
        donts: [...commonDonts, "Absolutely no electronics allowed inside"],
        crowdPattern: { type: "tourist" },
        specialDays: [{ day: "Sunday", multiplier: 2.0 }],
        peakMonths: [10, 11, 12]
    },
    {
        name: "Brihadeeswarar Temple",
        location: "Thanjavur, Tamil Nadu",
        state: "Tamil Nadu",
        description: "A Hindu temple dedicated to Shiva located in South bank of Kaveri river in Thanjavur.",
        imageUrl: "/temples/Brihadeeswarar/1.jpg",
        imageCredit: "Local Archive",
        ...generateRealisticRating(),
        timings: "6:00 AM - 9:00 PM",
        openHour: 6,
        closeHour: 21,
        baseWaitTime: 30,
        timingDetails: ["Morning: 6:00 AM - 12:30 PM", "Evening: 4:00 PM - 9:00 PM"],
        darshanTime: "1 hour",
        bestTimeToVisit: "Winter",
        lat: 10.7828,
        lng: 79.1316,
        deity: "Lord Shiva",
        significance: "Great Living Chola Temple",
        uniqueness: {
            spiritual: "Kumbabhishekam performed every 12 years.",
            scientific: "The 80-ton capstone was raised to the top (216 ft) using a 6km long inclined ramp. It is said clearly that the vimana does not cast a shadow at noon.",
            history: "Built by Raja Raja Chola I in 1010 AD."
        },
        dos: [...commonDos, "Admire the frescoes and inscriptions"],
        donts: [...commonDonts],
        crowdPattern: { type: "tourist" },
        specialDays: [{ day: "Monday", multiplier: 1.3 }],
        peakMonths: [1, 9, 10]
    },
    {
        name: "Dwarkadhish Temple",
        location: "Dwarka, Gujarat",
        state: "Gujarat",
        description: "Dedicated to Lord Krishna, who is worshipped here by the name Dwarkadhish, or 'King of Dwarka'.",
        imageUrl: "/temples/Dwarkadhish/1.jpg",
        imageCredit: "Local Archive",
        ...generateRealisticRating(),
        timings: "6:30 AM - 9:30 PM",
        openHour: 6,
        closeHour: 21,
        baseWaitTime: 45,
        timingDetails: ["Morning: 6:30 AM - 1:00 PM", "Evening: 5:00 PM - 9:30 PM"],
        darshanTime: "1-2 hours",
        bestTimeToVisit: "November-February",
        lat: 22.2376,
        lng: 68.9678,
        deity: "Lord Krishna",
        significance: "Char Dham",
        uniqueness: {
            spiritual: "Built on the site of Krishna's palace.",
            scientific: "Marine archaeology has found submerged ruins of ancient Dwarka nearby.",
            history: "Current structure is from the 16th century."
        },
        dos: [...commonDos, "Visit the Gomti Ghat"],
        donts: [...commonDonts],
        crowdPattern: { type: "pilgrimage" },
        specialDays: [{ day: "Janmashtami", multiplier: 2.5 }],
        peakMonths: [8, 11]
    },
    {
        name: "Shirdi Sai Baba Temple",
        location: "Shirdi, Maharashtra",
        state: "Maharashtra",
        description: "Dedicated to Sai Baba of Shirdi, who is revered by both Hindu and Muslim devotees.",
        imageUrl: "/temples/Shirdi_Sai_Baba/1.png",
        imageCredit: "AI Generated",
        ...generateRealisticRating(),
        timings: "4:00 AM - 11:15 PM",
        openHour: 4,
        closeHour: 23,
        baseWaitTime: 120,
        timingDetails: ["Kakad Aarti: 4:30 AM", "Shej Aarti: 10:30 PM"],
        darshanTime: "2-4 hours",
        bestTimeToVisit: "Weekdays",
        lat: 19.7668,
        lng: 74.4762,
        deity: "Sai Baba",
        significance: "Syncretism of religions",
        uniqueness: {
            spiritual: "Place where Sai Baba obtained Samadhi.",
            scientific: "The Neem tree here has leaves that are said to be sweet, unlike normal bitter neem.",
            history: "Temple built by a millionaire devotee in 1915."
        },
        dos: [...commonDos, "Book darshan pass online to skip long lines"],
        donts: [...commonDonts],
        crowdPattern: { type: "high_traffic" },
        specialDays: [{ day: "Thursday", multiplier: 2.0 }],
        peakMonths: [10, 12]
    },
    {
        name: "Lingaraj Temple",
        location: "Bhubaneswar, Odisha",
        state: "Odisha",
        description: "A Hindu temple dedicated to Harihara, a form of Shiva and Vishnu.",
        imageUrl: "/temples/Lingaraj/1.jpg",
        imageCredit: "Local Archive",
        ...generateRealisticRating(),
        timings: "5:00 AM - 9:00 PM",
        openHour: 5,
        closeHour: 21,
        baseWaitTime: 30,
        timingDetails: ["Closed: 1:00 PM - 3:30 PM"],
        darshanTime: "1 hour",
        bestTimeToVisit: "January-March",
        lat: 20.2382,
        lng: 85.8318,
        deity: "Harihara",
        significance: "Kalinga Architecture",
        uniqueness: {
            spiritual: "Self-originated Linga (Swayambhu).",
            scientific: "Built with sandstone and laterite, showcasing advanced medieval engineering.",
            history: "Built in 11th century by Somavamsi dynasty."
        },
        dos: [...commonDos, "Non-Hindus can view from a platform outside"],
        donts: [...commonDonts, "Non-Hindus not allowed inside"],
        crowdPattern: { type: "general" },
        specialDays: [{ day: "Monday", multiplier: 1.3 }],
        peakMonths: [2, 3]
    },
    {
        name: "Mahabodhi Temple",
        location: "Bodh Gaya, Bihar",
        state: "Bihar",
        description: "A UNESCO World Heritage Site, it is the place where the Buddha is said to have attained Enlightenment.",
        imageUrl: "/temples/Mahabodhi/1.jpg",
        imageCredit: "Local Archive",
        ...generateRealisticRating(),
        timings: "5:00 AM - 9:00 PM",
        openHour: 5,
        closeHour: 21,
        baseWaitTime: 20,
        timingDetails: [],
        darshanTime: "1-2 hours",
        bestTimeToVisit: "October-March",
        lat: 24.6952,
        lng: 84.9912,
        deity: "Lord Buddha",
        significance: "Buddhism's holiest site",
        uniqueness: {
            spiritual: "Site of the Bodhi Tree.",
            scientific: "One of the oldest brick structures in eastern India.",
            history: "Originally built by Emperor Ashoka in 3rd century BCE."
        },
        dos: [...commonDos, "Meditate under the Bodhi tree"],
        donts: [...commonDonts],
        crowdPattern: { type: "general" },
        specialDays: [{ day: "Full Moon", multiplier: 1.5 }],
        peakMonths: [5, 12]
    },
    {
        name: "Kamakhya Temple",
        location: "Guwahati, Assam",
        state: "Assam",
        description: "A Hindu temple dedicated to the mother goddess Kamakhya. It is one of the oldest of the 51 Shakti Pithas.",
        imageUrl: "/temples/Kamakhya/1.jpg",
        imageCredit: "Local Archive",
        ...generateRealisticRating(),
        timings: "5:30 AM - 5:30 PM",
        openHour: 5,
        closeHour: 17,
        baseWaitTime: 90,
        timingDetails: ["Closed: 1:00 PM - 2:30 PM"],
        darshanTime: "2-4 hours",
        bestTimeToVisit: "November-March",
        lat: 26.1663,
        lng: 91.7050,
        deity: "Goddess Kamakhya",
        significance: "Tantric fertility temple",
        uniqueness: {
            spiritual: "Celebrates the menstruation of the Goddess (Ambubachi Mela).",
            scientific: "A natural spring keeps the sanctum moist, which turns red (iron oxide) during monsoon.",
            history: "Rebuilt in 1565 by Chilarai."
        },
        dos: [...commonDos, "Respect the tantric rituals"],
        donts: [...commonDonts, "Avoid visiting during Ambubachi if you dislike crowds"],
        crowdPattern: { type: "high_traffic" },
        specialDays: [{ day: "Tuesday", multiplier: 1.2 }],
        peakMonths: [6]
    },
    {
        name: "Padmanabhaswamy Temple",
        location: "Thiruvananthapuram, Kerala",
        state: "Kerala",
        description: "One of the richest temples in the world with treasures worth over $20 billion. Features Lord Vishnu in reclining posture.",
        imageUrl: "/temples/Padmanabhaswamy/1.jpg",
        imageCredit: "Local Archive",
        ...generateRealisticRating(),
        timings: "3:30 AM - 7:30 PM",
        openHour: 3,
        closeHour: 20,
        baseWaitTime: 60,
        timingDetails: ["Closed: 12:00 PM - 5:00 PM"],
        darshanTime: "1 hour",
        bestTimeToVisit: "October-February",
        lat: 8.4826,
        lng: 76.9436,
        deity: "Lord Vishnu",
        significance: "Extreme Wealth and Mystery",
        uniqueness: {
            spiritual: "Vishnu lies in 'Anantha Shayana' posture.",
            scientific: "Vault B has a door with no nuts/bolts, rumored to be sealed by sound waves (Naga Bandham).",
            history: "Extensively renovated by Marthanda Varma in 18th century."
        },
        dos: [...commonDos, "Men must wear Dhoti, Women Saree"],
        donts: [...commonDonts, "Strict dress code enforced", "Non-Hindus not allowed"],
        crowdPattern: { type: "high_traffic" },
        specialDays: [],
        peakMonths: [1, 4]
    },
    {
        name: "Konark Sun Temple",
        location: "Konark, Odisha",
        state: "Odisha",
        description: "A 13th-century CE Sun Temple. The temple is shaped like a gigantic chariot with elaborate stone wheels, pillars and walls.",
        imageUrl: "/temples/Konark_Sun_Temple/1.jpg",
        imageCredit: "Local Archive",
        ...generateRealisticRating(),
        timings: "6:00 AM - 8:00 PM",
        openHour: 6,
        closeHour: 20,
        baseWaitTime: 30,
        timingDetails: ["Light & Sound show in evening"],
        darshanTime: "2 hours",
        bestTimeToVisit: "Winter",
        lat: 19.8876,
        lng: 86.0945,
        deity: "Surya (Sun God)",
        significance: "UNESCO World Heritage",
        uniqueness: {
            spiritual: "Chariot of the Sun God.",
            scientific: "Legends say the main idol was suspended in air by magnets. The wheels function as sundials.",
            history: "Built by Narasimhadeva I of Eastern Ganga Dynasty about 1250 CE."
        },
        dos: [...commonDos, "Hire a guide to explain the wheels"],
        donts: [...commonDonts, "Do not climb on the ruins"],
        crowdPattern: { type: "tourist" },
        specialDays: [{ day: "Sunday", multiplier: 1.5 }],
        peakMonths: [12, 1]
    },
    {
        name: "Mahakaleshwar Jyotirlinga",
        location: "Ujjain, Madhya Pradesh",
        state: "Madhya Pradesh",
        description: "One of the twelve Jyotirlingas. The idol is Dakshinamurti (facing south), a unique feature among Tantric traditions.",
        imageUrl: "/temples/Mahakaleshwar/1.jpg",
        imageCredit: "Local Archive",
        ...generateRealisticRating(),
        timings: "4:00 AM - 11:00 PM",
        openHour: 4,
        closeHour: 23,
        baseWaitTime: 90,
        timingDetails: ["Bhasma Aarti: 4:00 AM (Booking required)"],
        darshanTime: "2-3 hours",
        bestTimeToVisit: "October-March",
        lat: 23.1831,
        lng: 75.7681,
        deity: "Lord Shiva",
        significance: "Bhasma Aarti",
        uniqueness: {
            spiritual: "Only Jyotirlinga facing South (direction of Death), symbolizing mastery over time/death.",
            scientific: "Ancient timekeeping center of India (Prime Meridian passed through Ujjain).",
            history: "Mentioned in Puranas, rebuilt by Marathas."
        },
        dos: [...commonDos, "Book Bhasma Aarti online in advance"],
        donts: [...commonDonts],
        crowdPattern: { type: "pilgrimage" },
        specialDays: [{ day: "Monday", multiplier: 1.8 }],
        peakMonths: [2, 3]
    },
    {
        name: "Kailasa Temple",
        location: "Ellora, Maharashtra",
        state: "Maharashtra",
        description: "The largest monolithic rock-cut structure in the world, carved from a single rock face.",
        imageUrl: "/temples/Kailasa_Temple/1.jpg",
        imageCredit: "Local Archive",
        ...generateRealisticRating(),
        timings: "6:00 AM - 6:00 PM",
        openHour: 6,
        closeHour: 18,
        baseWaitTime: 20,
        timingDetails: ["Closed on Tuesdays"],
        darshanTime: "2-3 hours",
        bestTimeToVisit: "June-March",
        lat: 20.0238,
        lng: 75.1793,
        deity: "Lord Shiva",
        significance: "Architectural Miracle",
        uniqueness: {
            spiritual: "Modeled after Mt. Kailash.",
            scientific: "Carved TOP-DOWN from a single rock. 200,000 tons of rock removed without modern machinery (a mystery).",
            history: "Built by Rashtrakuta King Krishna I (8th Century)."
        },
        dos: [...commonDos, "Wear comfortable shoes for walking"],
        donts: [...commonDonts, "Do not scratch the rock walls"],
        crowdPattern: { type: "tourist" },
        specialDays: [],
        peakMonths: [11, 12]
    },
    {
        name: "Veerabhadra Temple",
        location: "Lepakshi, Andhra Pradesh",
        state: "Andhra Pradesh",
        description: "A stunning Vijayanagara style temple known for its hanging pillar.",
        imageUrl: "/temples/Veerabhadra_Lepakshi/1.png",
        imageCredit: "Local Archive",
        ...generateRealisticRating(),
        timings: "6:00 AM - 6:00 PM",
        openHour: 6,
        closeHour: 18,
        baseWaitTime: 15,
        timingDetails: [],
        darshanTime: "1-2 hours",
        bestTimeToVisit: "Winter",
        lat: 13.8037,
        lng: 77.6067,
        deity: "Veerabhadra (Shiva)",
        significance: "Hanging Pillar",
        uniqueness: {
            spiritual: "Spot where Jatayu fell after fighting Ravana.",
            scientific: "Features a 'Hanging Pillar' that does not touch the ground completely; a cloth can be passed under it. An engineering marvel.",
            history: "Built in 16th century by Vijayanagara governors."
        },
        dos: [...commonDos, "Test the hanging pillar with a cloth"],
        donts: [...commonDonts],
        crowdPattern: { type: "general" },
        specialDays: [],
        peakMonths: [12, 1]
    },
    {
        name: "Vittala Temple",
        location: "Hampi, Karnataka",
        state: "Karnataka",
        description: "An iconic temple in Hampi known for its Stone Chariot and Musical Pillars.",
        imageUrl: "/temples/Vittala_Hampi/1.png",
        imageCredit: "Local Archive",
        ...generateRealisticRating(),
        timings: "8:30 AM - 5:30 PM",
        openHour: 8,
        closeHour: 17,
        baseWaitTime: 20,
        timingDetails: [],
        darshanTime: "2 hours",
        bestTimeToVisit: "November-February",
        lat: 15.3350,
        lng: 76.4600,
        deity: "Lord Vittala (Vishnu)",
        significance: "Musical Pillars",
        uniqueness: {
            spiritual: "Center of Vijayanagara religion.",
            scientific: "56 Musical Pillars produce the 7 notes (Sa-Re-Ga-Ma...) when tapped. They are solid rock, not hollow.",
            history: "Built by Devaraya II (15th century)."
        },
        dos: [...commonDos, "Visit the stone chariot (on new 50 rupee note)"],
        donts: [...commonDonts, "Do not tap the pillars (protected now)"],
        crowdPattern: { type: "tourist" },
        specialDays: [],
        peakMonths: [11, 12, 1]
    },
    {
        name: "Jagannath Temple",
        location: "Puri, Odisha",
        state: "Odisha",
        description: "A famous Char Dham temple where Krishna is worshipped as Jagannath 'Lord of the Universe'.",
        imageUrl: "/temples/Jagannath_Puri/1.png",
        imageCredit: "Local Archive",
        ...generateRealisticRating(),
        timings: "5:00 AM - 11:00 PM",
        openHour: 5,
        closeHour: 23,
        baseWaitTime: 60,
        timingDetails: ["Mahaprasad available after 11 AM"],
        darshanTime: "1-2 hours",
        bestTimeToVisit: "October-February",
        lat: 19.8049,
        lng: 85.8179,
        deity: "Lord Jagannath",
        significance: "Char Dham, Rath Yatra",
        uniqueness: {
            spiritual: "Deities are made of wood and replaced every 12-19 years (Nabakalebara).",
            scientific: "Flag flows opposite to wind direction. No shadow of the main dome is ever seen. No birds fly over the dome.",
            history: "Built in 12th century by Anantavarman Chodaganga."
        },
        dos: [...commonDos, "Eat the Mahaprasad"],
        donts: [...commonDonts, "Non-Hindus strictly not allowed"],
        crowdPattern: { type: "pilgrimage" },
        specialDays: [{ day: "Rath Yatra", multiplier: 3.0 }],
        peakMonths: [6, 7]
    },
    {
        name: "Meenakshi Amman Temple",
        location: "Madurai, Tamil Nadu",
        state: "Tamil Nadu",
        description: "A historic Hindu temple located on the southern bank of the Vaigai River. Known for its towering Gopurams.",
        imageUrl: "/temples/Meenakshi_Amman/1.jpg",
        imageCredit: "Local Archive",
        ...generateRealisticRating(),
        timings: "5:00 AM - 9:00 PM",
        openHour: 5,
        closeHour: 21,
        baseWaitTime: 45,
        timingDetails: ["Closed: 12:30 PM - 4:00 PM"],
        darshanTime: "2 hours",
        bestTimeToVisit: "October-March",
        lat: 9.9195,
        lng: 78.1193,
        deity: "Meenakshi (Parvati)",
        significance: "Architectural Wonder",
        uniqueness: {
            spiritual: "Shiva performed the cosmic dance (Tandava) here.",
            scientific: "Acoustics of the 1000-pillar hall are magnificent. Some pillars produce musical notes when struck.",
            history: "Rebuilt by Nayak rulers in 16th century."
        },
        dos: [...commonDos, "Visit the 1000 Pillar Hall"],
        donts: [...commonDonts],
        crowdPattern: { type: "high_traffic" },
        specialDays: [{ day: "Friday", multiplier: 1.4 }],
        peakMonths: [4]
    },
    {
        name: "Siddhivinayak Temple",
        location: "Mumbai, Maharashtra",
        state: "Maharashtra",
        description: "A prominent Ganesh temple in Mumbai, popular with politicians and Bollywood stars.",
        imageUrl: "/temples/Siddhivinayak_Mumbai/1.png",
        imageCredit: "Local Archive",
        ...generateRealisticRating(),
        timings: "5:30 AM - 9:50 PM",
        openHour: 5,
        closeHour: 22,
        baseWaitTime: 90,
        timingDetails: ["Kakad Aarti: 5:30 AM", "Shej Aarti: 9:50 PM"],
        darshanTime: "2-3 hours",
        bestTimeToVisit: "Weekdays",
        lat: 19.0169,
        lng: 72.8304,
        deity: "Lord Ganesha",
        significance: "Wish Fulfilling",
        uniqueness: {
            spiritual: "Ganesha's trunk turns to the right (Siddhi Vinayak), which is rare and considered powerful.",
            scientific: "Modern architecture ensures the Kalash above the idol is plated with 1500kg gold.",
            history: "Built in 1801."
        },
        dos: [...commonDos, "Use the online queue app"],
        donts: [...commonDonts],
        crowdPattern: { type: "high_traffic" },
        specialDays: [{ day: "Tuesday", multiplier: 2.5 }],
        peakMonths: [8, 9]
    },
    {
        name: "Golden Temple",
        location: "Amritsar, Punjab",
        state: "Punjab",
        description: "The holiest Gurdwara of Sikhism. AKA Sri Harmandir Sahib.",
        imageUrl: "/temples/Golden_Temple/1.jpg",
        imageCredit: "Local Archive",
        ...generateRealisticRating(),
        timings: "2:30 AM - 2:00 AM",
        openHour: 2,
        closeHour: 26,
        baseWaitTime: 45,
        timingDetails: ["Palki Sahib ceremony at night"],
        darshanTime: "1-2 hours",
        bestTimeToVisit: "October-March",
        lat: 31.6200,
        lng: 74.8765,
        deity: "Guru Granth Sahib",
        significance: "Sikhism's Holiest Shrine",
        uniqueness: {
            spiritual: "Open to people of all faiths (4 doors).",
            scientific: "The Sarovar (pool) is fed by the Ravi river and has an advanced filtration system. The gold plating is pure 24 karat.",
            history: "Founded by Guru Ram Das in 1577."
        },
        dos: ["Cover your head (mandatory)", "Wash feet before entering", "Eat at the Langar"],
        donts: ["No tobacco/alcohol", "Do not sit with feet pointing at holy book"],
        crowdPattern: { type: "high_traffic" },
        specialDays: [{ day: "Sunday", multiplier: 1.5 }],
        peakMonths: [4, 11]
    }
];

export { templesData, generateRealisticRating };
